In [22]:
import numpy as np

eps = 0.0000000001
inf = 1000000000000000000000000000000

In [23]:
P = 3
Q = 3
A = np.array([[0, 1, 2, 3],
              [0, 0, 1, 2],
              [0, 2, 2, 3]], dtype = float)

In [24]:
# agents:   0, 1, ... P-1
# resource: 0, 1, ... Q-1, Q

B = np.zeros(shape=(P, Q + 1), dtype=float)
C = np.zeros(shape=(P, Q + 1), dtype=int)

for agent in range(P):
    for resource in range(Q + 1):
        if agent == 0:
            B[agent][resource] = A[agent][resource]
            C[agent][resource] = resource
        else:
            best_resource = 0
            best_profit = -inf
            for q in range(resource + 1):
                profit = A[agent][q] + B[agent - 1][resource - q]
                if profit > best_profit:
                    best_profit = profit
                    best_resource = q
            B[agent][resource] = best_profit
            C[agent][resource] = best_resource


In [25]:
print("B = ")
print(B)

print("C = ")
print(C)

B = 
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 2. 3. 4.]]
C = 
[[0 1 2 3]
 [0 0 0 0]
 [0 1 1 1]]


In [26]:
skolko = np.zeros(shape=(P,), dtype=int)

p = P-1
q = Q

while p >= 0:
    skolko[p] = C[p][q]
    q = q - C[p][q]
    p = p - 1

print(f"skolko = {skolko}")

skolko = [2 0 1]
