In [12]:
import numpy as np

eps = 0.0000000001
inf = 1000000000000000000000000000000

In [13]:
n = 7
v = np.array([4, 1, 2, 6, 3, 6, 2], dtype=int)
c = np.array([9, 8, 6, 9, 2, 5, 4], dtype = float)
B = 15

In [14]:
opt = np.zeros(shape=(n, B + 1), dtype=float)
x = np.zeros(shape=(n, B + 1), dtype=int)

for k in range(n):
    for b in range(B + 1):
        if k == 0:
            if v[k] <= b:
                opt[k][b] = c[k]
                x[k][b] = 1
            else:
                opt[k][b] = 0
                x[k][b] = 0
        else: # k >= 2
            if v[k] <= b:
                opt1 = opt[k - 1][b]
                opt2 = c[k] + opt[k - 1][b - v[k]]
                if opt1 < opt2:
                    opt[k][b] = opt2
                    x[k][b] = 1
                else:
                    opt[k][b] = opt1
                    x[k][b] = 0
            else:
                opt[k][b] = opt[k - 1][b]
                x[k][b] = 0

In [15]:
print("opt = ")
print(opt)

print("x = ")
print(x)

opt = 
[[ 0.  0.  0.  0.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
 [ 0.  8.  8.  8.  9. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17.]
 [ 0.  8.  8. 14. 14. 17. 17. 23. 23. 23. 23. 23. 23. 23. 23. 23.]
 [ 0.  8.  8. 14. 14. 17. 17. 23. 23. 23. 23. 26. 26. 32. 32. 32.]
 [ 0.  8.  8. 14. 14. 17. 17. 23. 23. 23. 25. 26. 26. 32. 32. 32.]
 [ 0.  8.  8. 14. 14. 17. 17. 23. 23. 23. 25. 26. 26. 32. 32. 32.]
 [ 0.  8.  8. 14. 14. 18. 18. 23. 23. 27. 27. 27. 29. 32. 32. 36.]]
x = 
[[0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1]]


In [16]:
brali = np.zeros(shape=(n,))

k = n - 1
b = B

while k >= 0:
    brali[k] = x[k][b]

    if brali[k] == 1:
        b = b - v[k]
    k = k - 1

print(f"brali = {brali}")

brali = [1. 1. 1. 1. 0. 0. 1.]
